[project]
name = "mymovies"
version = "1.0.0"
description = "Enhanced Movie Website with Advanced Features"
requires-python = ">=3.11"
dependencies = [
    "flask>=2.3.0",
    "flask-wtf>=1.1.0",
    "werkzeug>=2.3.0",
    "requests>=2.31.0",
]
